FROM ubuntu:latest

RUN apt-get update && \
  apt-get install -y iproute2 iptables traceroute iputils-ping net-tools curl telnet netcat-openbsd

COPY externo.sh /usr/local/bin/externo.sh
RUN chmod +x /usr/local/bin/externo.sh

COPY socket-client.sh /usr/local/bin/socket.sh
RUN chmod +x /usr/local/bin/socket.sh

CMD ["/bin/bash", "-c", "/usr/local/bin/externo.sh && tail -f /dev/null"]

