FROM ubuntu:latest

RUN apt-get update && \
  apt-get install -y iproute2 iptables traceroute iputils-ping net-tools curl telnet netcat-openbsd

COPY server.sh /usr/local/bin/server.sh
RUN chmod +x /usr/local/bin/server.sh

COPY socket-server.sh /usr/local/bin/socket.sh
RUN chmod +x /usr/local/bin/socket.sh

CMD ["/bin/bash", "-c", "/usr/local/bin/server.sh && tail -f /dev/null"]

