version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build: ./producer
    depends_on:
      - rabbitmq
  consumer1:
    build: ./consumer
    depends_on:
      - rabbitmq
  consumer2:
    build: ./consumer
    depends_on:
      - rabbitmq