# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agenda.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61genda.proto\x12\x06\x61genda\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n\x06Pessoa\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12)\n\ttelefones\x18\x04 \x03(\x0b\x32\x16.agenda.NumeroTelefone\x12\x30\n\x0clast_updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nencontrado\x18\x06 \x01(\x08\"\x8f\x01\n\x0eNumeroTelefone\x12\x0e\n\x06numero\x18\x01 \x01(\t\x12\x31\n\x04tipo\x18\x02 \x01(\x0e\x32#.agenda.NumeroTelefone.TipoTelefone\":\n\x0cTipoTelefone\x12\x0b\n\x07\x43\x45LULAR\x10\x00\x12\x0f\n\x0bRESIDENCIAL\x10\x01\x12\x0c\n\x08TRABALHO\x10\x02\"\x1d\n\x08Resposta\x12\x11\n\tresultado\x18\x01 \x01(\t2a\n\x06\x41genda\x12-\n\tadicionar\x12\x0e.agenda.Pessoa\x1a\x10.agenda.Resposta\x12(\n\x06\x62uscar\x12\x0e.agenda.Pessoa\x1a\x0e.agenda.Pessoab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agenda_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PESSOA']._serialized_start=58
  _globals['_PESSOA']._serialized_end=220
  _globals['_NUMEROTELEFONE']._serialized_start=223
  _globals['_NUMEROTELEFONE']._serialized_end=366
  _globals['_NUMEROTELEFONE_TIPOTELEFONE']._serialized_start=308
  _globals['_NUMEROTELEFONE_TIPOTELEFONE']._serialized_end=366
  _globals['_RESPOSTA']._serialized_start=368
  _globals['_RESPOSTA']._serialized_end=397
  _globals['_AGENDA']._serialized_start=399
  _globals['_AGENDA']._serialized_end=496
# @@protoc_insertion_point(module_scope)
